#pragma once
// Auto-generated config page

static const char CONFIG_HTML[] PROGMEM = 
  "<!DOCTYPE html>\n"
  "<html lang=\"es\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
  "<title>Stream Deck Config</title>\n"
  "<style>\n"
  "*{margin:0;padding:0;box-sizing:border-box}\n"
  "body{font-family:-apple-system,sans-serif;background:#1a1a2e;color:#eee;min-height:100vh;display:flex;flex-direction:column;align-items:center;padding:20px 12px}\n"
  "h1{font-size:22px;margin-bottom:6px;background:linear-gradient(135deg,#667eea,#764ba2);-webkit-background-clip:text;-webkit-text-fill-color:transparent}\n"
  ".sub{color:#888;margin-bottom:20px;font-size:13px}\n"
  ".status{display:flex;gap:12px;margin-bottom:16px;font-size:12px}\n"
  ".badge{padding:3px 10px;border-radius:12px}\n"
  ".bt-on{background:#1a3a5c;color:#4aa8ff}.bt-off{background:#3b1111;color:#f87171}\n"
  ".grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;max-width:600px;width:100%;margin-bottom:20px}\n"
  ".btn-card{aspect-ratio:1.3;border-radius:12px;display:flex;flex-direction:column;align-items:center;justify-content:center;cursor:pointer;transition:all .15s;box-shadow:0 3px 10px rgba(0,0,0,.4);border:2px solid transparent;gap:4px;position:relative}\n"
  ".btn-card:hover{transform:translateY(-2px);border-color:rgba(255,255,255,.3)}\n"
  ".btn-card .label{font-size:14px;font-weight:700;text-shadow:0 1px 2px rgba(0,0,0,.5)}\n"
  ".btn-card .hint{font-size:10px;opacity:.6;max-width:90%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}\n"
  ".btn-card .edit-icon{position:absolute;top:6px;right:8px;font-size:12px;opacity:0;transition:opacity .2s}\n"
  ".btn-card:hover .edit-icon{opacity:.8}\n"
  ".overlay{display:none;position:fixed;inset:0;background:rgba(0,0,0,.7);z-index:100;align-items:center;justify-content:center}\n"
  ".overlay.active{display:flex}\n"
  ".modal{background:#16213e;border-radius:16px;padding:24px;width:400px;max-width:95vw;box-shadow:0 15px 50px rgba(0,0,0,.5);max-height:90vh;overflow-y:auto}\n"
  ".modal h2{margin-bottom:16px;font-size:18px}\n"
  ".field{margin-bottom:14px}\n"
  ".field label{display:block;font-size:12px;color:#aaa;margin-bottom:4px}\n"
  ".field input,.field select{width:100%;padding:8px 12px;border-radius:8px;border:1px solid #333;background:#0f1a30;color:#eee;font-size:14px;outline:none}\n"
  ".field input:focus{border-color:#667eea}\n"
  ".field input[type=color]{height:40px;padding:3px;cursor:pointer}\n"
  ".pills{display:flex;gap:4px}\n"
  ".pills label{flex:1;text-align:center;padding:7px;border-radius:6px;background:#0f1a30;border:1px solid #333;cursor:pointer;font-size:12px;transition:all .2s}\n"
  ".pills input{display:none}\n"
  ".pills label:has(input:checked){border-color:#667eea;background:#1a2540;color:#667eea}\n"
  ".presets{display:grid;grid-template-columns:repeat(3,1fr);gap:4px;margin-top:8px}\n"
  ".preset{padding:6px;border-radius:6px;background:#0f1a30;border:1px solid #333;color:#ccc;font-size:11px;cursor:pointer;text-align:center}\n"
  ".preset:hover{border-color:#667eea;color:#fff}\n"
  ".preset .pi{font-size:16px;display:block}\n"
  ".sep{border-top:1px solid #2a2a3e;margin:16px 0}\n"
  ".upload-row{display:flex;align-items:center;gap:8px}\n"
  ".upload-btn{padding:6px 14px;border-radius:6px;background:#667eea;color:#fff;font-size:12px;font-weight:600;cursor:pointer}\n"
  ".upload-name{font-size:12px;color:#888;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}\n"
  ".toggle-row{display:flex;align-items:center;justify-content:space-between;cursor:pointer}\n"
  ".toggle-row input{display:none}\n"
  ".toggle-sw{width:40px;height:22px;background:#333;border-radius:11px;position:relative;transition:background .2s}\n"
  ".toggle-sw::after{content:\"\";position:absolute;top:2px;left:2px;width:18px;height:18px;background:#888;border-radius:50%;transition:all .2s}\n"
  ".toggle-row input:checked+.toggle-sw{background:#667eea}\n"
  ".toggle-row input:checked+.toggle-sw::after{left:20px;background:#fff}\n"
  ".actions{display:flex;gap:8px;margin-top:18px}\n"
  ".actions button{flex:1;padding:10px;border-radius:8px;border:none;font-size:14px;font-weight:600;cursor:pointer}\n"
  ".btn-save{background:#667eea;color:#fff}\n"
  ".btn-cancel{background:#2a2a3e;color:#aaa}\n"
  ".btn-clear{background:#dc2626;color:#fff}\n"
  ".help{font-size:10px;color:#555;margin-top:4px}\n"
  "</style></head><body>\n"
  "<h1>Stream Deck Config</h1>\n"
  "<p class=\"sub\">by Bits y Tornillos</p>\n"
  "<div class=\"status\"><span class=\"badge\" id=\"btStatus\">BT...</span><span class=\"badge\" style=\"background:#0d3320;color:#4ade80\">WiFi ON</span></div>\n"
  "<div class=\"grid\" id=\"grid\"></div>\n"
  "<div class=\"overlay\" id=\"overlay\">\n"
  "<div class=\"modal\">\n"
  "<h2>Boton <span id=\"eIdx\"></span></h2>\n"
  "<div class=\"field\"><label>Nombre</label><input type=\"text\" id=\"eLabel\" maxlength=\"19\"></div>\n"
  "<div class=\"field\"><label>Color</label><input type=\"color\" id=\"eColor\"></div>\n"
  "<div class=\"field\"><label>Accion</label>\n"
  "<div class=\"pills\">\n"
  "<label><input type=\"radio\" name=\"aType\" value=\"0\"><span>Ninguna</span></label>\n"
  "<label><input type=\"radio\" name=\"aType\" value=\"1\"><span>URL</span></label>\n"
  "<label><input type=\"radio\" name=\"aType\" value=\"2\"><span>Teclado</span></label>\n"
  "<label><input type=\"radio\" name=\"aType\" value=\"4\"><span>Texto</span></label>\n"
  "</div></div>\n"
  "<div id=\"presetBox\" style=\"display:none\"><div class=\"presets\" id=\"presets\"></div></div>\n"
  "<div class=\"field\"><label>Valor</label><input type=\"text\" id=\"eAction\" placeholder=\"https://...\"><div class=\"help\" id=\"eHelp\"></div></div>\n"
  "<div class=\"sep\"></div>\n"
  "<div class=\"field\"><label>Icono (imagen)</label>\n"
  "<div class=\"upload-row\"><label class=\"upload-btn\" for=\"eIcon\">Subir</label><input type=\"file\" id=\"eIcon\" accept=\"image/*\" style=\"display:none\"><span class=\"upload-name\" id=\"eIconName\">-</span></div></div>\n"
  "<div class=\"field\"><label>Tamano icono</label><div class=\"pills\">\n"
  "<label><input type=\"radio\" name=\"iSize\" value=\"0\"><span>S</span></label>\n"
  "<label><input type=\"radio\" name=\"iSize\" value=\"1\"><span>M</span></label>\n"
  "<label><input type=\"radio\" name=\"iSize\" value=\"2\"><span>L</span></label>\n"
  "<label><input type=\"radio\" name=\"iSize\" value=\"3\"><span>XL</span></label>\n"
  "</div></div>\n"
  "<div class=\"field\"><label>Marco</label><div class=\"pills\">\n"
  "<label><input type=\"radio\" name=\"bStyle\" value=\"0\"><span>No</span></label>\n"
  "<label><input type=\"radio\" name=\"bStyle\" value=\"1\"><span>Fino</span></label>\n"
  "<label><input type=\"radio\" name=\"bStyle\" value=\"2\"><span>Grueso</span></label>\n"
  "<label><input type=\"radio\" name=\"bStyle\" value=\"3\"><span>Glow</span></label>\n"
  "</div></div>\n"
  "<div class=\"field\"><label class=\"toggle-row\"><span>Mostrar texto</span><input type=\"checkbox\" id=\"eShowLabel\" checked><span class=\"toggle-sw\"></span></label></div>\n"
  "<div class=\"actions\">\n"
  "<button class=\"btn-cancel\" onclick=\"closeModal()\">Cancelar</button>\n"
  "<button class=\"btn-clear\" onclick=\"clearBtn()\">Limpiar</button>\n"
  "<button class=\"btn-save\" onclick=\"saveBtn()\">Guardar</button>\n"
  "</div></div></div>\n"
  "<script>\n"
  "let B=[],eI=-1,customIcon=null;\n"
  "const presets=[\n"
  "{i:\"🔊\",l:\"Vol +\",v:\"vol_up\"},{i:\"🔉\",l:\"Vol -\",v:\"vol_down\"},{i:\"🔇\",l:\"Mute\",v:\"vol_mute\"},\n"
  "{i:\"⏯\",l:\"Play\",v:\"play_pause\"},{i:\"⏭\",l:\"Next\",v:\"next_track\"},{i:\"⏮\",l:\"Prev\",v:\"prev_track\"},\n"
  "{i:\"📋\",l:\"Copy\",v:\"ctrl+c\"},{i:\"📌\",l:\"Paste\",v:\"ctrl+v\"},{i:\"↩\",l:\"Undo\",v:\"ctrl+z\"},\n"
  "{i:\"💾\",l:\"Save\",v:\"ctrl+s\"},{i:\"🔍\",l:\"Find\",v:\"ctrl+f\"},{i:\"📸\",l:\"Screenshot\",v:\"gui+shift+s\"}];\n"
  "const helps={0:\"\",1:\"URL completa (https://...)\",2:\"Atajo: ctrl+c, vol_up, play_pause...\",4:\"Texto que se escribira\"};\n"
  "const phs={0:\"\",1:\"https://www.amazon.es\",2:\"ctrl+shift+a\",4:\"Hola mundo\"};\n"
  "\n"
  "async function load(){const r=await fetch(\"/api/buttons\");B=await r.json();render();}\n"
  "function render(){\n"
  "const g=document.getElementById(\"grid\");g.innerHTML=\"\";\n"
  "B.forEach((b,i)=>{const d=document.createElement(\"div\");d.className=\"btn-card\";\n"
  "d.style.background=`rgb(${b.r},${b.g},${b.b})`;\n"
  "let h=b.action?b.action.replace(\"https://\",\"\").replace(\"http://\",\"\").substring(0,20):\"\";\n"
  "d.innerHTML=`<span class=\"edit-icon\">✎</span><span class=\"label\">${b.label}</span><span class=\"hint\">${h}</span>`;\n"
  "d.onclick=()=>openModal(i);g.appendChild(d);});}\n"
  "\n"
  "function openModal(i){eI=i;const b=B[i];customIcon=null;\n"
  "document.getElementById(\"eIdx\").textContent=i+1;\n"
  "document.getElementById(\"eLabel\").value=b.label;\n"
  "document.getElementById(\"eColor\").value=rgbHex(b.r,b.g,b.b);\n"
  "document.getElementById(\"eAction\").value=b.action||\"\";\n"
  "document.querySelector(`input[name=aType][value=\"${b.actionType}\"]`).checked=true;\n"
  "document.querySelector(`input[name=iSize][value=\"${b.iconSizeIdx}\"]`).checked=true;\n"
  "document.querySelector(`input[name=bStyle][value=\"${b.borderStyle}\"]`).checked=true;\n"
  "document.getElementById(\"eShowLabel\").checked=b.showLabel;\n"
  "document.getElementById(\"eIconName\").textContent=\"-\";\n"
  "updHelp();document.getElementById(\"overlay\").classList.add(\"active\");}\n"
  "\n"
  "function closeModal(){document.getElementById(\"overlay\").classList.remove(\"active\");eI=-1;}\n"
  "function rgbHex(r,g,b){return\"#\"+[r,g,b].map(x=>x.toString(16).padStart(2,\"0\")).join(\"\");}\n"
  "function hexRgb(h){const m=h.match(/^#?(\\w{2})(\\w{2})(\\w{2})$/);return m?[parseInt(m[1],16),parseInt(m[2],16),parseInt(m[3],16)]:[100,100,100];}\n"
  "\n"
  "function updHelp(){\n"
  "const t=+document.querySelector(\"input[name=aType]:checked\").value;\n"
  "document.getElementById(\"eHelp\").textContent=helps[t]||\"\";\n"
  "document.getElementById(\"eAction\").placeholder=phs[t]||\"\";\n"
  "const pb=document.getElementById(\"presetBox\");\n"
  "if(t===2){pb.style.display=\"\";const pg=document.getElementById(\"presets\");pg.innerHTML=\"\";\n"
  "presets.forEach(p=>{const d=document.createElement(\"div\");d.className=\"preset\";\n"
  "d.innerHTML=`<span class=\"pi\">${p.i}</span>${p.l}`;\n"
  "d.onclick=()=>{document.getElementById(\"eAction\").value=p.v;document.getElementById(\"eLabel\").value=p.l;};\n"
  "pg.appendChild(d);});}else pb.style.display=\"none\";}\n"
  "\n"
  "document.querySelectorAll(\"input[name=aType]\").forEach(r=>r.addEventListener(\"change\",updHelp));\n"
  "document.getElementById(\"overlay\").addEventListener(\"click\",e=>{if(e.target.id===\"overlay\")closeModal();});\n"
  "document.getElementById(\"eIcon\").addEventListener(\"change\",function(e){\n"
  "const f=e.target.files[0];if(!f)return;\n"
  "document.getElementById(\"eIconName\").textContent=f.name;\n"
  "const r=new FileReader();r.onload=ev=>{customIcon=ev.target.result.split(\",\")[1];};r.readAsDataURL(f);});\n"
  "\n"
  "async function saveBtn(){\n"
  "const i=eI,c=hexRgb(document.getElementById(\"eColor\").value);\n"
  "const data={label:document.getElementById(\"eLabel\").value||String(i+1),\n"
  "r:c[0],g:c[1],b:c[2],\n"
  "action:document.getElementById(\"eAction\").value,\n"
  "actionType:+document.querySelector(\"input[name=aType]:checked\").value,\n"
  "iconSizeIdx:+document.querySelector(\"input[name=iSize]:checked\").value,\n"
  "borderStyle:+document.querySelector(\"input[name=bStyle]:checked\").value,\n"
  "showLabel:document.getElementById(\"eShowLabel\").checked};\n"
  "if(customIcon)data.icon=customIcon;\n"
  "await fetch(\"/api/btn/\"+i,{method:\"POST\",headers:{\"Content-Type\":\"application/json\"},body:JSON.stringify(data)});\n"
  "B[i]=data;render();closeModal();}\n"
  "\n"
  "async function clearBtn(){\n"
  "const i=eI;\n"
  "await fetch(\"/api/btn/\"+i,{method:\"POST\",headers:{\"Content-Type\":\"application/json\"},\n"
  "body:JSON.stringify({label:String(i+1),r:100,g:100,b:100,action:\"\",actionType:0,iconSizeIdx:1,borderStyle:0,showLabel:true})});\n"
  "load();closeModal();}\n"
  "\n"
  "function updBT(){fetch(\"/api/status\").then(r=>r.json()).then(d=>{\n"
  "const el=document.getElementById(\"btStatus\");\n"
  "el.textContent=d.bt?\"BT Conectado\":\"BT Esperando...\";\n"
  "el.className=\"badge \"+(d.bt?\"bt-on\":\"bt-off\");});}\n"
  "\n"
  "load();setInterval(updBT,3000);updBT();\n"
  "</script></body></html>";
